### PR TITLE
Add default icon for videojs-contrib-quality-menu

### PR DESCRIPTION
**Pull request by unixfox**
This PR adds the icon vjs-icon-cog so that there is a default icon shown in the control bar.

List of all the icons: https://videojs.github.io/font/

I hope it's the correct way to add this default icon, if not please tell me.

Thank you!

### CODE REVIEW

**Comment by mister-ben** [comment]
This shouldn't be necessary, the icon will show up as it is, from here:

https://github.com/videojs/videojs-contrib-quality-menu/blob/0a74ab864790907eafdabf3788e9156b96469c92/src/plugin.scss#L15-L33

Do you have some conflicting style perhaps?

**Comment by unixfox** [comment]
Thank you for your reply.

For some reason, the icon was not showing in the player bar unless I specified a CSS class with an icon like it's done in `jfujita/videojs-http-source-selector`: 

https://github.com/jfujita/videojs-http-source-selector/blob/d036cebb63880bf9a489a01561ca04e84235bde1/src/components/SourceMenuButton.js#L40

I'll try to see if there are some conflicting styles, but at first glance I do not see any.
CSS code: https://github.com/iv-org/invidious/blob/master/assets/css/player.css
Javascript code: https://github.com/iv-org/invidious/blob/master/assets/js/player.js

**Review by misteroneill — COMMENTED** [review]
Thanks for the PR!

I wasn't able to reproduce a missing gear icon (it shows for me when running `npm start` and opening `localhost:9999`).

I think this is a reasonable change, though, because the fewer places we have the `content:` values in CSS, the better. Should we also remove the CSS that @mister-ben pointed out?

**Review by misteroneill — APPROVED** [review]

**Comment by misteroneill** [comment]
Thanks for the PR @unixfox, it's a big help!

**Pull request merged**
